export  class ACESSO {
  static ROLES = {
    MENSAGERIA: {
      MANTER: 'MSG_MANTER_MENSAGEM'
    },
    ADMINISTRACAO: {
      AD_ENV_MSG_USU: 'AD_ENV_MSG_USU',
      AD_ENV_MSG_USU_APP: 'AD_ENV_MSG_USU_APP',
    },
    CREDENCIADA: {
      MANTER: 'CRD_CREDENCIADA_MANTER'
    },
    CREDENCIAMENTO: {
      GESTAO: 'CRD_CREDENCIAMENTO_GST',
      OPERADOR: 'CRD_CREDENCIAMENTO_OPR'
    },
    SERVICO_CREDENCIADOS: {
      MANTER: 'CRD_SERVICO_MANTER'
    },
    GESTAO_BANCA_EXAMINADORA: {
      MANTER: 'GBE_BANCA_EXAMINADORA_MANTER'
    },
    GERENCIAMENTO_TRIAGEM_HABILITACAO: {
      MANTER: 'GTH_GERENC_TRIAGEM_MANTER'
    },
    TRANSFERENCIA_ELETRONICA: {
      MANTER: 'RNV_TRANSFERENCIA'
    },
    ATENDIMENTO_DIGITAL: {
      MANTER: 'GAT_ATEN_DIG_MANTER',
      CONSULTAR: 'GAT_ATEN_DIG_CONSULTAR',
      ATRIB_RESPONSAVEL: 'GAT_ATEN_DIG_ATRIB_RESP',
      AVOCAR: 'GAT_ATEN_DIG_AVOCAR'
    },
    PESQUISAS: {
      MANTER: 'PESQ_SATI_MANTER',
      CONSULTAR: 'PESQ_SATI_CONSULTAR'
    },
    FINANCEIRO: {
      administradores_SIGOFI: 'administradores_SIGOFI',
      gestores_SIGOFI: 'gestores_SIGOFI'
    },
    INFRACOES: {
      HIST_CONSULTAR: 'HIST_INFR_CONSULTAR'
    }, 
    
    // TODO MUDAR PARA ROLE CORRETA
    REGISTRO_CERTIFICADO: {
      MANTER: 'CRD_CREDENCIAMENTO_GST'
    }
  };
}
