export enum TipoSituacaoSolicitacaoEnum {
    REGISTRADO = 1,
    AGUARDANDO_PAGAMENTO = 2,
    AGUARDANDO_AVALIACAO = 3,
    PENDENCIAS_DE_AJUSTE = 4,
    AGUARDANDP_APROVACAO_DIRETORIA = 5,
    FINALIZADO = 6,
    RECUSADO = 7,
    AGUARDANDO_PAGAMENTO_PROVA = 8,
    EXCLUIDO = 9,
    SOLICITACAO = 10,
	AGUARDANDO_SOLICITACAO_PAGAMENTO=11
}


