export enum IndiceCalculoEnum {
    IGP_DI = 'IGP-DI (FGV)',
    CUB = 'CUB (Sinduscon)',
    CUB_SC = 'CUB-SC (Sinduscon)',
    IGP_M = 'IGP-M (FGV)',
    INCC_DI = 'INCC-DI (FGV)',
    INPC = 'INPC (IBGE)',
    IPC = 'IPC (Fipe)',
    IPC_DI = 'IPC-DI (FGV)',
    IPCA = 'IPCA (IBGE)',
    IPCA_E = 'IPCA-E (IBGE)',
    IVAR = 'IVAR (FGV)',
    CDI = 'CDI',
    SELIC = 'Selic (cálculo simples)',
    TBF = 'TBF',
    TJLP = 'TJLP (BACEN)',
    TR = 'TR (Bacen)',
    OUTROS = 'Outros',
}