export enum SituacaoTramitacaoEnum {
  CADASTRADO = 'CADASTRADO',
  ENVIADO_PARA_ANALISE = 'ENVIADO PARA ANÁLISE',
  EM_RETIFICACAO = 'EM RETIFICAÇÃO',
  APROVADO = 'APROVADO',
  AGUARDANDO_PUBLICACAO = 'AGUARDANDO PUBLICAÇÃO',
  PUBLICADO = 'PUBLICADO'
}